spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shavigh_db
    username: shavigh
    password: shavigh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
